
<center>
  <!-- This table contains the login form. -->
  <table id="login-table">
	<tr>
	  <td valign="top">
		<?php if (isset($this->failedAuthentication)): ?>
		  <p class="error">
			The supplied login or password is incorrect.
			Please try again.</p>
		<?php endif; ?>

		<!-- This is where the form will be displayed. -->
		<div id="login-form"></div>
	  </td>
	</tr>
  </table>
</center>

<!-- Include the JavaScript used to build the login panel. -->
<script src="/js/src/action/login/DoLogin.js?<?php print time(); ?>"></script>
<script src="/js/src/action/login/ForgotPassword.js?<?php print time(); ?>"></script>
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/login/LoginPanel.js?<?php print time(); ?>"></script>
<script>
  Ext.onReady(function() {
	  // Create the login panel.
	  var loginPanel = new ui.panel.login.LoginPanel();
	  loginPanel.render('login-form');
	  loginPanel.setInitialFocus();
  });
</script>


