
<h1>About Us</h1>

<br/>

<img align="right" src="/images/framework/about.jpg"/>

<p>Milestone Intelligence Group, Inc. was formed with the purpose of providing
highly skilled system engineering and software services to our customers
enabling project success. Our specialists bring decades of experience
supporting customers in the Intelligence and Defense communities. We are a
veteran-owned small business, and we recognize that successful partnerships are
based on open and direct communication, mutual respect, and the ability to
adapt to evolving capabilities within National Security and the Signals
Intelligence space.</p>

<p>Milestones mark the completion of significant customer events, yet lay the
foundation and framework for subsequent mission activity and evolution. We
pride ourselves on enabling our customers to meet these objectives while being
viewed as critical members of their teams - teams requiring respect and
integrity to achieve continued success.</p>

<p>Our specialists hold numerous credentials including Top Secret/SCI security
clearances, PMI and ITIL certifications, professional development
certifications and post-graduate degrees. We are proud to provide a productive
environment for our employees which fosters teamwork, creativity, and
retention. Our company provides comprehensive benefit packages featuring
competitive salaries. Milestone Intelligence Group strives to maintain a
healthy work-life balance for all of our employees.</p>

<p>Our core competencies lie in the following fields:
<ul>
  <li class="li">Cyberspace Security</li>
  <li class="li">Software Engineering and Development</li>
  <li class="li">System Engineering</li>
  <li class="li">Test and Evaluation Engineering</li>
</ul></p>

<p>Milestone also supports customers in the following non-core areas:
<ul>
  <li class="li">Acquisition Support</li>
  <li class="li">Process Management</li>
  <li class="li">Project and Program Management</li>
</ul></p>

<h1>Leadership</h1>

<h2>Doug Stewart, President / CEO</h2>

<img align="left" src="/images/leadership/doug.jpg"
     style="padding-right: 10px;"/>

<b>Education Summary:</b>

<p>
<li style="margin-left: 20px;">Degree in Communications Technology</li>
<li style="margin-left: 20px;">Certified Software Test Manager</li>
<li style="margin-left: 20px;">Certified Capability Maturity Model
Integration (CMMI)</li></p>

<b>Experience Summary:</b>

<p>35 years supporting the Intelligence Community as an IT professional
performing all aspects of Program Management, System Engineering, Test and
Evaluation (T&amp;E), and operational support. Involved with various levels of
project support for the National Security Agency/Central Security Service
(NSA/CSS) to include field site deployments. As a Systems Engineering Technical
Assistance (SETA) contractor, lead T&amp;E teams on Acquisition Category (ACAT)
1D programs. While serving in the United States Air Force, managed 120
multi-service military personnel supporting all elements of software
development, system administration, and system design, servicing UNIX and
Windows NT applications.</p>

<b>Personal Summary:</b>

<p>Doug was born in Barre, Vermont on November 24, 1956, and grew up in the
state of Massachusetts. He joined the United States Air Force at the age of 21
and lived in countries such as Japan, Greece and England. Doug retired from the
Air Force in 1997 as a Master Sergeant and immediately started working as a
defense contractor. He worked for a few defense contractors over the past 13
years before deciding to start Milestone in 2010.</p>

<p>He is happily married to his wife Joann of over 34 years and has two
wonderful daughters as well as a granddaughter. He is active in the community
by helping those with drug addictions in the City of Baltimore get into recovery
programs. His hobbies include sports, church and spending time with his family.
He is an avid golfer and is on the golf course as much as time will allow.</p>


<h2>Dave Krause, Principal / COO</h2>

<img align="left" src="/images/leadership/dave.jpg"
     style="padding-right: 10px;"/>

<b>Education Summary:</b>

<p>
<li style="margin-left: 20px;">B.S. in Mechanical Engineering / Mathematics
Minor (University of Maryland)</li>
<li style="margin-left: 20px;">Project Management Professional (PMP)</li></p>

<b>Experience Summary:</b>

<p>Dave brings over 20 years of customer experience in the Government Industry
and Commercial arenas towards designing, integrating and deploying distributed
high-performance IT systems.  He works closely with the leadership team in
overseeing all engineering activities while managing the technical and
financial delivery across all contract vehicles.  His experience includes the
technical delivery and management of over 90 IT professionals across $40M+ in
contracts as the Principal Solution Architect/Technical Strategist for a
Fortune 100 company.  As a Certified Systems Integration Specialist, he
developed and instructed courses in Software Performance Testing, Performance
Architecture and Test Automation.  He is passionate towards challenging each
employee to share their experiences with the team while bringing their "A" game
to solve customer challenges.</p>

<b>Personal Summary:</b>

<p>A Maryland native and Terrapin alumni, Dave is an avid music fan and
musician. His passion for statistics and sports led him to develop spreadsheets
and projection models for Rotisserie baseball going back to 1986 (where weekly
stats were hand-entered from the newspaper). He lost over 125 pounds following
high school, signed up for a marathon on a dare in 2003 and has become enamored
with the sport completing 19 marathons since that time. He and his family are
extremely committed towards supporting causes including Pediatric Inflammatory
Bowel Disease (IBD) and Breast Cancer research having raised over $85,000 in
support of these efforts. He and his wife Jill have been happily married since
1997 and are blessed with 4 wonderful children.</p>




<h2>Mike Day, Principal / CTO</h2>

<img align="left" src="/images/leadership/mike.jpg"
     style="padding-right: 10px;"/>

<b>Education Summary:</b>

<p>
<li style="margin-left: 20px;">B.S. Computer Science, UMBC</li></p>

<b>Experience Summary:</b>

<p>15 years of experience performing all levels of software development and
engineering, for both large and small systems. Responsible for designing and
building large-scale systems, and involved in many types of technology
demonstration and prototyping activities. Has a depth of experience in building
high-volume analytical query applications, designing and building cloud-based
analytics and algorithms, implementing data ingest flows and query analytics
against multi-terabyte data warehouses, and many other technology areas.</p>

<b>Personal Summary:</b>

<p>Mike was born in Covington, Kentucky on June 9, 1981, and grew up in
Cincinnati, Ohio. At the age of 16, he move with his family to West Virginia
where his father became the pastor of a small church. After high school, he
attended West Virginia University Institute of Technology, double-majoring in
computer science and mathematics. During this time, he accepted a Cooperative
Education tour at the National Security Agency, and shortly thereafter
transferred to UMBC and moved to Maryland. He has since become a defense
contractor and has worked for several companies both at NSA and at the
Pentagon. In 2010, he was approached by Doug Stewart and agreed to co-found
Milestone.</p>

<p>He and his wife, Jessica, have been happly married since 2002, and his
daughter, Kara, was born in 2006. His hobbies include reading, playing
bridge, and tournament bass fishing.</p>

