
<h1>Careers with Milestone</h1>

<br/>

<img align="right" src="/images/framework/careers.jpg"/>

<p>At Milestone Intelligence Group, we do our best to cultivate business-minded
professionals that are looking to be the best of the best in their chosen
careers. We are always looking for top-notch talent in our core competency
areas, and our competitive salaries and benefits in conjunction with our
employee-first attitude gives us an edge over our competition. Let Milestone
be the final building block on your career path.</p>

<p>To express interest in working with us, please contact us via <i>careers
[at] milestoneintelligence.com</i>, and include your resume. Feel free to
reference a specific <a href="/openings/index">open position</a> if you
like.</p>

