
<h1>Community Support &amp; Giving Back</h1>

<br/>

<p>Milestone feels strongly about supporting or local community through
charities and fund raisers, and giving back to members of the military for
everything they have sacrificed so that we can enjoy the lives we have. We
describe below a few of the activities in which we are involved.</p>


<h2>Fort Meade Student Scholarship</h2>

<p>We at Milestone Intelligence Group, Inc. look to our young adults as our
future and want to do everything we can to support their efforts. With this
in mind, Milestone awarded a scholarship to...</p>

<h2>Anne Arundel County Science Fair</h2>

<p>The wife of Milestone employee Steve Espinosa is a board member for Anne
Arundel County Schools (or something like that). Steve Espinosa and his wife
assisted in the organization and management of the science fair, and Milestone
CEO Doug Stewart, and CTO Mike Day, acted as judges during the competition.
After a day of asking questions to middle and high school students about their
projects, Milestone awarded three cash prizes to students for their efforts.
</p>

<h2>Paralyzed Veterans of America and Wounded Warriors Bass Fishing
Tournaments</h2>

<p>Every year, Milestone is a major sponsor of the "Capitol Clash" bass
fishing tournament hosted on the Potomac River in Southern Maryland by the
Paralyzed Veterans of America (PVA) Bass Tour (<a href="http://pvabasstour.org"
target="_blank">pvabasstour.org</a>) in collaboration with the Maryland BASS
Nation (MBN, <a href="http://www.mdbass.com/" target="_blank">mdbass.com</a>).
This event brings 50-60 wounded veterans from Walter Reed and other places
around the country to compete in bass boats in a large two-day tournament, and
an additional 20-30 bank fisherman tournament. Milestone and other sponsors
contribute money and resources to provide the participants with their own
fishing rods, reels, and tackle, as well as providing food, drinks and rooms to
many of the participants over the course of the weekend. Milestone employee Ron
Hines is a member of the PVA Committee within the MBN, and raises tens of
thousands of dollars each year to support the event. He also spends a lot of
time and hard work helping with the logistics involved in the event, from
filling tackle boxes with terminal tackle and lures, to hauling over 100 cases
of water to Smallwood State Park, and many other aspects of the event. Ron
also acts as a boat captain during the event, and takes his assigned angler
out on the water to catch the big ones. Milestone co-founder Mike Day also
supports the event by providing whatever help is needed, is a boat captain
during the tournament, and has also been the camera boat to help the event
photographers capture those live shots of the anglers in action.</p>

<h2>Southern Arizona Select Basketball Club</h2>

<p>Through Milestone employee Frank Diaz working out of Fort Huachucha, Arizona,
Milestone sponsored the Southern Arizona Select (SAS) Basketball Club. SAS is a
locally based youth activities non-profit 501(c)(3) organization operating five
competitive basketball teams spanning the ages of 9-17. SAS supports all
spectrums of youth, but places special focus on at-risk populations and
leverages operating agreements with local youth centers in pursuit of this core
organizational goal.</p>

<h2>Stand Up for Kids - Poker Run</h2>

<p>
<a
href="http://standupforkids.givezooks.com/events/2013-stand-up-for-kids-poker-run">The
Stand up for Kids Poker Run website</a>.</p>

<h2>MAGIC Foundation - Walk for MAGIC</h2>

<p>For the past several years, Milestone has been a sponsor of Walk for MAGIC.
This community event raises money for kids with growth disorders.  <a
href="http://www.magicfoundation.org/www">The MAGIC Foundation website</a>.
</p>

<h2>Trinity Golf Tournament</h2>

<p>What does this event support?</p>

