
<h1>Contacting Us</h1>

<br/>

<img align="right" src="/images/framework/contact.jpg"/>

<p>There are several ways in which to contact Milestone personnel. The primary
methods used to contact us are outlined below.</p>

<table id="contact-table">
  <!-- Add the corporate mailing address. -->
  <tr>
    <td class="contact-label" nowrap>Mailing Address:</td>
    <td class="contact-value" nowrap>
	  7050 Hi Tech Drive, Suite 105<br>
	  Hanover, Maryland 21076
	</td>
  </tr>

  <!-- Add the corporate phone number. -->
  <tr>
    <td class="contact-label" nowrap>Phone:</td>
    <td class="contact-value" nowrap>410-220-2079</td>
  </tr>

  <!-- Add the corporate fax number. -->
  <tr>
    <td class="contact-label" nowrap>Fax:</td>
    <td class="contact-value" nowrap>410-242-6552</td>
  </tr>

  <!-- Add the email lists. -->
  <tr>
    <td class="contact-label" nowrap>Email Lists:</td>
    <td>
	  <table cellpadding="0" cellspacing="0">
	    <tr>
		  <td class="email">exec [at] milestoneintelligence.com</td>
		  <td class="email-description">
			President and principals
		  </td>
		</tr>
	    <tr>
		  <td class="email">careers [at] milestoneintelligence.com</td>
		  <td class="email-description">
			Job-related questions, resumes, etc.
		  </td>
		</tr>
	    <tr>
		  <td class="email">info [at] milestoneintelligence.com</td>
		  <td class="email-description">
			General information
		  </td>
		</tr>
	    <tr>
		  <td class="email">contracts [at] milestoneintelligence.com</td>
		  <td class="email-description">
			Contracts, proposals, agreements, etc.
		  </td>
		</tr>
	    <tr>
		  <td class="email">hr [at] milestoneintelligence.com</td>
		  <td class="email-description">
			Human resources and benefits
		  </td>
		</tr>
	    <tr>
		  <td class="email">web [at] milestoneintelligence.com</td>
		  <td class="email-description">
			Web site and employee portal
		  </td>
		</tr>
	  </table>
	  <br/>
	  <small>*Note that <code>[at]</code> is used instead of <code>@</code>
	  to help prevent these email addresses from being spammed by web
	  crawlers.</small>
	</td>
  </tr>
</table>

