
<table id="page-table">
  <tr>
    <td id="left-content">

	  <h1>Welcome to Milestone Intelligence Group</h1>

	  <p>Milestone Intelligence Group, Inc. is a veteran-owned defense
	  contracting company supporting national-level Intelligence Community
	  customers. We specialize in the intelligence field supporting Department
	  of Defense and Homeland Security agencies. Feel free to read more <a
	  href="/index/about">about us</a> and the <a
	  href="/index/services">services</a> we provide.</p>

    </td>
    <td id="right-content">

	  <h1>Core Services</h1>

	  <p>We focus on the following core competency areas:
	  <ul id="core-services">
		<li>Cyberspace Security</li>
		<li>Software Engineering</li>
		<li>System Engineering</li>
		<li>Test and Evaluation</li>
	  </ul></p>

    </td>
  </tr>
</table>

