
<!-- Add the page title. -->
<h1>Privacy Policy and Terms of Use</h1>

<br/>

<p>Milestone Intelligence Group, Inc. (herinafter referred to as "Milestone")
maintains this web site as a service to its employees and visitors. The Privacy
Policy and Terms of Use set forth below govern your use of this web site, and
by using the web site you agree to be bound by them. Therefore, please ready
the Privacy Policy and Terms of Use carefully before you use this web site. If
you do not agree with our Privacy Policy and Terms of Use, please do not use
this web site.</p>

<h2>PRIVACY POLICY</h2>

<h3>Log Files</h3>

<p>Like most web sites, this web site logs your IP address, browser type, hits
on particular pages and other general traffic information. This information is
not linked to personally identifiable information and you remain anonymous.</p>

<h3>Use of Personal Information</h3>

<p>If you give us personal information, for any purpose, we will not share that
information with any third party, except to the extent necessary to complete
transactions or if we believe that it is appropriate to share such information
in order to comply with the law, to enforce or apply the Privacy Policy or
Terms of Use or to protect the rights, property or safety of the web site, any
user of the site, Milestone or any of its directors, officers, employees,
agents or affiliated organizations.</p>

<h3>Cookies</h3>

<p>A "cookie" is a file that is sent from a web server to your web browser and
placed on your computer. When you initially visit the web site we create a
cookie for your computer and then use it to track your clicks as you go through
the site. There is no personal information stored within the cookie itself and
we cannot use cookies to retrieve personal information about you or from your
computer. While your activity may be tracked while you are at our web site, we
do not use cookies to track your activity before or after you leave the site.
We use cookies to keep your style preferences for the layout of the site, and
to manage your web session as you navigate through the site.</p>

<h3>Posting of Personal Information</h3>

<p>Please be aware that whenever you voluntarily disclose personal information
online - for example, on a message board or through email - that information
can be collected and used by others. By disclosing personal information online,
you may make that information available to others who will use it to send you
unsolicited messages or for other purposes you may not desire or intend.</p>

<h3>Children's Online Privacy Protection Act (COPPA)</h3>

<p>While our web site is not subject to COPPA, we understand that it is very
important to maintain their privacy. Therefore, our policy is that we will not
knowingly collect, use or distribute to third parties any personally
identifiable information from any child under 13 years old without verifiable
parental consent and not knowingly allow any child under 13 years old to
publicly post or distribute personally identifiable information without
verifiable parental consent.</p>

<h2>TERMS OF USE</h2>

<h3>Trademarks and Copyrights - All Rights Reserved</h3>

<p>Milestone reserves all of its rights under and does not grant any express or
implied rights to you or any other user of the web site under any trademark,
copyright, trade secret or other intellectual property law, except as provided
below with regard to the use of downloaded messages. This web site and all of
the text, graphics, pictures, audio messages, video materials, downloadable
materials and all other materials and content on the web site are copyrighted
by and are the property of Milestone. You may not use them in any manner
without express written consent.</p>

<h3>Message Boards and other Posted Information</h3>

<p>Any message board posting or other information that you submit for posting
on our web site is subject to these Terms of Use and the Privacy Policy. You
cannot submit defamatory, obscene or otherwise harmful or offensive information
or materials or information or materials that violate or infringe upon
intellectual property rights or other rights. Children under 13 years old
cannot post messages without verifiable parental consent. By submitting any
information to the web site, you agree and warrant to Milestone that your
message meets all of the conditions for submission. Your message may be
reviewed by one or more of our staff members or other individuals before it is
published, and we have the right to edit your message before it is published.
We have the right to publish any message on our web site and to use it in any
other form or in any other materials, including without limitation promotional
and other marketing-related materials. We also have the right not to publish
any message or to remove it from the web site or other media at any time and
for any reason without notice. Notwithstanding the above, Milestone expressly
disclaims any responsibility or liability for any material communicated by
third parties through this web site, including without limitation any message
published on the web site. Message board postings do not necessarily reflect
the views of Milestone or its agents or affiliated organizations.</p>

<h3>Disclaimer of Warranties</h3>

<p>All materials and other content of this web site or accessible from this web
site are provided on an "as is" basis and Milestone expressly disclaims any
express or implied warranties or conditions of any kind, including without
limitation any warranties of merchantability, fitness for a particular purpose
or use, title or non-infringement.</p>

<h3>Limitation of Liability</h3>

<p>By using this web site you agree that Milestone and each of its directors,
officers, employees, other agents and affiliated organizations shall not be
liable to you for any damage of any kind arising from or related to the use of
this web site or any web site for which a link is provided on this site.</p>

<h3>Changes</h3>

<p>We reserve the right to make changes to this web site and the policies and
conditions that govern the use of the web site at any time. We encourage you to
review the web site and these terms periodically for any updates or changes.
Your continued access or use of our web site shall be deemed your acceptance of
these changes and the reasonableness of these standards for notice of
changes.</p>

<h3>Applicable Law</h3>

<p>Use of this web site and any claim or dispute arising from or related to use
of this web site is governed by the laws of the State of Maryland, without
regard to any rule or principle regarding conflicts of laws. The exclusive
jurisdiction and venue of any such claim or dispute shall be in the state and
federal courts for Anne Arundel County, Maryland.</p>

<h3>Contact Information</h3>

<p>If you have any questions regarding our Privacy Policy or Terms of Use, you
can contact us as outlined on the <a href="/index/contact">Contact Us</a>
page.</p>

