
<h1>Our Partners</h1>

<br/>

<img align="right" src="/images/framework/partners.jpg"/>

<p>We at Milestone understand the importance of strategic partnerships, with
both large and small companies. We are intimately familiar with our own
capabilities, and continually strive for partnerships where we can lend our
strengths and augment our weaknesses. We pride ourselves in being a highly
sought-after team member based on the integrity, dedication, and reputation of
our employees. Companies we partner with are listed below.</p>


<table id="partner-table" cellspacing="18">
  <tr>
    <td class="partner-image">
	  <a href="http://www.lmco.com/"><img src="/images/partners/lockheed.jpg"
		   alt="Lockheed Martin"/></a>
	</td>
    <td class="partner-image">
	  <a href="http://www.keywcorp.com/"><img src="/images/partners/keyw.jpg"
		   alt="KEYW"/></a>
	</td>
  </tr>
  <tr>
    <td class="partner-image">
	  <a href="http://www.northropgrumman.com/"><img
		   src="/images/partners/northrop.jpg" alt="Northrop Grumman"/></a>
	</td>
    <td class="partner-image">
	  <a href="http://www.ptgcorp.com/"><img src="/images/partners/ptg.jpg"
		   alt="Performance Technology Group"/></a>
	</td>
  </tr>
  <tr>
    <td class="partner-image">
	  <a href="http://www.sra.com/"><img src="/images/partners/sra.jpg"
		   alt="Systems Research and Applications Corporation"/></a>
	</td>
    <td class="partner-image">
	  <a href="http://www.the-si.com/"><img src="/images/partners/thesi.jpg"
		   alt="The SI Corporation"/></a>
	</td>
  </tr>
  <tr>
    <td class="partner-image">
	  <a href="http://www.clearedgeit.com/"><img src="/images/partners/clearedge.jpg"
		   alt="ClearEdge IT Solutions"/></a>
	</td>
    <td class="partner-image">
	  <a href="http://www.csc.com"><img src="/images/partners/csc.jpg"
		   alt="CSC"/></a>
	</td>
  </tr>
  <tr>
    <td class="partner-image">
	  <a href="http://www.raytheon.com/"><img src="/images/partners/raytheon.jpg"
		   alt="Raytheon"/></a>
	</td>
    <td class="partner-image">
	  <a href="http://www.freedomconsultinggroup.com/"><img src="/images/partners/freedom.jpg"
		   alt="Freedom Consulting Group"/></a>
	</td>
  </tr>
  <tr>
    <td class="partner-image">
	  <a href="http://alionscience.com/"><img src="/images/partners/alion.jpg"
		   alt="Alion Science and Technology Corporation"/></a>
	</td>
    <td class="partner-image">
	  <a href="http://www.eaglebankcorp.com/"><img src="/images/partners/eaglebank.jpg"
		   alt="Eagle Bank"/></a>
	</td>
  </tr>
</table>

