

<!-- Check to see if there was an exception. -->
<?php if (isset($this->exception)): ?>

  <!-- Add the page header -->
  <h1>Application Error</h1>

  <br/>

  <p>The application encountered a problem with your request.</p>

  <div id="error-message">
	<pre>
	  <small>
<?php echo $this->exception->getMessage(); ?>
	  </small>
	</pre>
  </div>

  <div id="error-stack">
	<pre>
	  <small>
<?php echo $this->exception->getTraceAsString(); ?>
	  </small>
	</pre>
  </div>

<?php else: ?>

  <!-- Add the page header -->
  <h1>Page Not Found</h1>

  <br/>

  <p>The page you are looking for was not found. Please check the spelling of
  the URL carefully, try searching for content you know is on the page, check
  the navigation links above, or just proceed back to the <a href="/">home
  page</a>.

<?php endif; ?>

