
<!-- Meta tags explaining the contents of this page. -->
<meta name="robots" content="index, follow"/>
<meta name="author" content="Mike Day"/>
<meta name="keywords" content="Defense Systems Software Testing Engineering Security Cyber"/>
<?php if ($this->title == "Contact Us"): ?>
<meta name="description" content="Contacting the defense contracting company Milestone Intelligence Group via Email, Phone, or Mail"/>
<?php elseif ($this->title == "About Us"): ?>
<meta name="description" content="About the defense contracting company Milestone Intelligence Group"/>
<?php elseif ($this->title == "Our Services"): ?>
<meta name="description" content="Technology Services provided the defense contracting company Milestone Intelligence Group"/>
<?php elseif ($this->title == "Our Partners"): ?>
<meta name="description" content="Technology companies acting as Partners to the defense contracting company Milestone Intelligence Group"/>
<?php elseif ($this->title == "Careers"): ?>
<meta name="description" content="How to apply for a job with the defense contracting company Milestone Intelligence Group to begin a career in the intelligence community"/>
<?php elseif ($this->title == "Leadership"): ?>
<meta name="description" content="A description of the corporate executives responsible for the defense company Milestone Intelligence Group"/>
<?php elseif ($this->title == "Privacy Policy and Terms of Service"): ?>
<meta name="description" content="A description of the privacy rights afforded to visitors of the Milestone Intelligence Group web site"/>
<?php elseif ($this->title == "Login"): ?>
<meta name="description" content="The login page for the Milestone Intelligence Group web site"/>
<?php elseif ($this->title == "Timesheets"): ?>
<meta name="description" content="The employee timesheets page for the Milestone Intelligence Group web site"/>
<?php else: ?>
<meta name="description" content="Supporting and protecting the war fighter through the successful implementation of advanced systems, software, and technologies."/>
<?php endif; ?>

<meta name="google-site-verification" content="XCoq8NZ1MNEwBKgyooJFoVqQwHnvJUKC64kKTgmZrkA"/>

