
<!-- Add the holiday management scripts. -->
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/util/ErrorMessage.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/Holiday.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/HolidayStore.js?<?php print time(); ?>"></script>
<script src="/js/src/action/holiday/DoHolidayAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/holiday/DoHolidayDelete.js?<?php print time(); ?>"></script>
<script src="/js/src/action/holiday/DoHolidaySearch.js?<?php print time(); ?>"></script>
<script src="/js/src/action/holiday/ShowHolidayAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/holiday/ShowHolidayGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/tbar/HolidayToolbar.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/HolidayGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/holiday/HolidayAddPanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/holiday/HolidayUpdatePanel.js?<?php print time(); ?>"></script>

