
<!-- Add the supervisor management scripts. -->
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/util/ErrorMessage.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoApprove.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoComplete.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoDisapprove.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoEdit.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoFix.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoSave.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoSearch.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoView.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/DoViewAuditLog.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/Disapprove.js?<?php print time(); ?>"></script>
<script src="/js/src/action/supervisor/Approve.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/AuditLog.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/TimesheetStatus.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/AuditLogStore.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/SupervisedStore.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/tbar/SupervisedToolbar.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/AuditLogGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/SupervisedGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/supervisor/choosePayPeriod.js?<?php print time(); ?>"></script>

