
<!-- Add the profile management scripts. -->
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/util/ErrorMessage.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/Employee.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/Supervisor.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/SupervisorStore.js?<?php print time(); ?>"></script>
<script src="/js/src/action/employee/DoProfileUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/employee/ProfileUpdatePanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/SupervisorGrid.js?<?php print time(); ?>"></script>

