
<!-- Add the contract management scripts. -->
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/util/ErrorMessage.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/Contract.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/ContractEmployee.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/Employee.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/ContractEmployeeStore.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/ContractStore.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/EmployeeStore.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/DoContractActivate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/DoContractAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/DoContractDeactivate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/DoContractDelete.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/DoContractSearch.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/DoContractUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/ShowContractAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/ShowContractEmployees.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/ShowContractGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contract/ShowContractUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contractemployee/DoAssignmentAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contractemployee/DoAssignmentDelete.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contractemployee/DoAssignmentSearch.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contractemployee/DoAssignmentUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contractemployee/ShowAssignmentAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contractemployee/ShowAssignmentUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contractemployee/ShowContractEmployeeGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/tbar/ContractToolbar.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/tbar/ContractEmployeeToolbar.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/ContractEmployeeGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/ContractGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/contract/ContractAddPanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/contract/ContractUpdatePanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/contractemployee/AssignmentAddPanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/contractemployee/AssignmentUpdatePanel.js?<?php print time(); ?>"></script>

