
<!-- Add the contact management scripts. -->
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/util/ErrorMessage.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/Contact.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/ContactStore.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contact/DoContactAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contact/DoContactDelete.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contact/DoContactSearch.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contact/DoContactUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contact/ShowContactAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/contact/ShowContactUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/tbar/ContactToolbar.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/ContactGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/contact/ContactAddPanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/contact/ContactUpdatePanel.js?<?php print time(); ?>"></script>

