
<!-- Add the payroll management scripts. -->
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/util/ErrorMessage.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/DoExport.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/DoSearch.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/DoUnexport.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/DoUnverify.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/DoVerify.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/DoView.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/DoViewAuditLog.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/Unverify.js?<?php print time(); ?>"></script>
<script src="/js/src/action/payroll/Verify.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/AuditLog.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/TimesheetStatus.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/AuditLogStore.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/PayrollStore.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/tbar/PayrollToolbar.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/AuditLogGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/PayrollGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/payroll/choosePayPeriod.js?<?php print time(); ?>"></script>

