
<link rel="stylesheet" type="text/css"
	  href="/js/ext-3.1.1/examples/ux/fileuploadfield/css/fileuploadfield.css"/>

<script type="text/javascript"
		src="/js/ext-3.1.1/examples/ux/fileuploadfield/FileUploadField.js"></script>

<!-- Add the forms display scripts. -->
<script src="/js/src/util/io/ServerIO.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/util/ErrorMessage.js?<?php print time(); ?>"></script>
<script src="/js/src/data/model/Form.js?<?php print time(); ?>"></script>
<script src="/js/src/data/store/FormStore.js?<?php print time(); ?>"></script>
<script src="/js/src/action/form/DoFormDelete.js?<?php print time(); ?>"></script>
<script src="/js/src/action/form/DoFormDownload.js?<?php print time(); ?>"></script>
<script src="/js/src/action/form/DoFormSearch.js?<?php print time(); ?>"></script>
<script src="/js/src/action/form/ShowFormAdd.js?<?php print time(); ?>"></script>
<script src="/js/src/action/form/ShowFormUpdate.js?<?php print time(); ?>"></script>
<script src="/js/src/action/form/ShowFormGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/tbar/FormToolbar.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/grid/FormGrid.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/form/FormDescriptionPanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/form/FormAddPanel.js?<?php print time(); ?>"></script>
<script src="/js/src/ui/panel/form/FormUpdatePanel.js?<?php print time(); ?>"></script>

